import 'dart:ui';

Color primaryColor= const Color(0xFF1E576C);
Color primaryColor2= const Color(0xFFBCE9F4);
String tokenT= 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAxNjk5MjcsImlhdCI6MTcxMDE2MjcyNywicm9sZSI6InVzZXIiLCJ1c3IiOiJncHNfcHJvamVjdCJ9.l-ggKZOsoAk8mhGzJVS1v0xcGN7LqRG8on4Xr4hEPXM';
String tokenL= 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAxNjk5MjcsImlhdCI6MTcxMDE2MjcyNywicm9sZSI6InVzZXIiLCJ1c3IiOiJncHNfcHJvamVjdCJ9.l-ggKZOsoAk8mhGzJVS1v0xcGN7LqRG8on4Xr4hEPXM';
